"""
Data models and schemas for SmartResolve AI.
Uses Pydantic for strict schema enforcement, data validation, and JSON serialization.
"""

from enum import Enum
from typing import Optional, List
from pydantic import BaseModel, Field


class CategoryEnum(str, Enum):
    BILLING = "Billing & Payments"
    TECHNICAL = "Technical Support"
    ACCOUNT = "Account & Access"
    SECURITY = "Security & Fraud"
    ORDERS = "Orders & Delivery"
    PRODUCT = "Product & Features"
    GENERAL = "General Inquiry"


class UrgencyEnum(str, Enum):
    LOW = "Low"
    MEDIUM = "Medium"
    HIGH = "High"
    CRITICAL = "Critical"


class TeamEnum(str, Enum):
    BILLING_TEAM = "Billing & Payments Team"
    TECH_SUPPORT = "Technical Support (Tier 2/3)"
    ACCOUNT_SECURITY = "Identity & Access Management"
    SECURITY_OPS = "Security Operations Center (SOC)"
    LOGISTICS = "Orders & Fulfillment Team"
    PRODUCT_MGMT = "Product Experience Team"
    CUSTOMER_CARE = "Customer Care (Tier 1)"
    HUMAN_TRIAGE = "Human Review Queue (Uncertain Triage)"


class TicketInput(BaseModel):
    """Input payload representing a customer support ticket."""
    ticket_id: str = Field(..., description="Unique ticket identifier (e.g. T001)")
    subject: str = Field(..., description="Short subject line of the support ticket")
    body: str = Field(..., description="Detailed message/body of the ticket")
    customer_tier: Optional[str] = Field(default="Standard", description="Customer tier: Standard, Pro, Enterprise")


class TriageOutput(BaseModel):
    """Structured output generated by the AI Triage Agent."""
    ticket_id: str = Field(..., description="Identifier matching the input ticket")
    category: CategoryEnum = Field(..., description="Primary classified category")
    urgency: UrgencyEnum = Field(..., description="Classified urgency level")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Model confidence score between 0.0 and 1.0")
    assigned_team: TeamEnum = Field(..., description="Target department or routing queue")
    human_review_required: bool = Field(..., description="Flag indicating if confidence is below threshold (<0.75)")
    reason: str = Field(..., description="Explainable reasoning behind classification & routing")
    recommended_action: str = Field(..., description="Suggested immediate next step for the resolving agent")
    extracted_keywords: List[str] = Field(default_factory=list, description="Key terms identified during triage")
    estimated_sla_hours: int = Field(default=24, description="Target SLA resolution turnaround in hours")


class BatchSummary(BaseModel):
    """Aggregated metrics for a batch triage execution."""
    total_tickets: int
    auto_routed_count: int
    human_review_count: int
    critical_urgency_count: int
    average_confidence: float
